### ISSUE TITLE
error when make -j4 project

### ISSUE THREAD

**Issue by luan1412167** [markson14/Face-Recognition-Cpp#2]
Hi markson14!
Thanks for your repo. I'm facing issue when run make project 
`/mnt/data/Face-Recognition-Cpp/facetracking.hpp:28:7: error: a storage class can only be specified for objects and functions
 const extern class MTCNN;`
Can you suggest me way to fix it? thanks so much.

**Comment by markson14** [comment]
@luan1412167 
In my case, it just a warning instead of an error so I didn't fix this. Maybe it doesn't need `const` here. you can try:
`const extern class MTCNN` to `class MTCNN`. 
This works for me.

**Comment by luan1412167** [comment]
hi @markson14.
Thanks for your reply. I have done like that but get an error.
`/mnt/data/Face-Recognition-Cpp/facetracking.hpp: In constructor ‘FR_MFN_Deploy::FR_MFN_Deploy(std::__cxx11::string)’:
/mnt/data/Face-Recognition-Cpp/facetracking.hpp:55:31: error: variable ‘std::ifstream json_in’ has initializer but incomplete type
         std::ifstream json_in(modelFolder + format("/deploy_graph_%s.json", arcface_model));`

**Comment by luan1412167** [comment]
@markson14 thanks for your reply. it worked. Your repo is so useful.
