### ISSUE TITLE
How to create deploy_lib_y1-arcface-emore_109.so file using arcface resnet 50?

### ISSUE THREAD

**Issue by luan1412167** [markson14/Face-Recognition-Cpp#3]
Hi markson14
Thanks for your repo. It's so useful.
Can you share me a way to create deploy_lib_y1-arcface-emore_109.so file using different backbone? I want to generate feature vector having 512 element. I'm using linux.
Thanks

**Comment by markson14** [comment]
you may refer to [TVM tutorial](https://docs.tvm.ai/tutorials/relay_quick_start.html#save-and-load-compiled-module) first. I will upload an example code later

**Comment by luan1412167** [comment]
@markson14 I have converted successful. thank you
