### ISSUE TITLE
detection with retinaface speeds too much time

### ISSUE THREAD

**Issue by jayle19930918** [markson14/Face-Recognition-Cpp#4]
Thank you for your work! I compiled the model using TVM at Windows10 successfully and got the correct bouding box of face. But it needs 1200ms to detect one frame which is so strange. I do no know what is the problem.

**Comment by markson14** [comment]
> Thank you for your work! I compiled the model using TVM at Windows10 successfully and got the correct bouding box of face. But it needs 1200ms to detect one frame which is so strange. I do no know what is the problem.

It could be the problems:
1. tvm complier target.
2. Hardware limitation. I'm using MBP 15' as testing env.
3. Too large input size

you can check out the listed issues.

**Comment by jayle19930918** [comment]
> > Thank you for your work! I compiled the model using TVM at Windows10 successfully and got the correct bouding box of face. But it needs 1200ms to detect one frame which is so strange. I do no know what is the problem.
> 
> It could be the problems:
> 
> 1. tvm complier target.
> 2. Hardware limitation. I'm using MBP 15' as testing env.
> 3. Too large input size
> 
> you can check out the listed issues.

Thanks for you suggestions! The pretrained model model I compiled was RetinaFace-R50, which is a medium size model with ResNet50 backbone. Then I found the MobileNet0.25 model and compiled it. Now it works well!
